//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=tcp:lazynews.database.windows.net,1433;Initial Catalog=NewsDB;Persist Secu" +
            "rity Info=False;User ID=lazynews;Password=1CalOmE6TKxio2O!k2;MultipleActiveResul" +
            "tSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;")]
        public string NewsDBConnectionString {
            get {
                return ((string)(this["NewsDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:lazynews.database.windows.net;Initial Catalog=NewsDB;Persist Secu" +
            "rity Info=True;User ID=lazynews")]
        public string NewsDBConnectionString1 {
            get {
                return ((string)(this["NewsDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:lazynews.database.windows.net;Initial Catalog=NewsDB;Persist Secu" +
            "rity Info=True;User ID=lazynews;Password=1CalOmE6TKxio2O!k2")]
        public string NewsDBConnectionString2 {
            get {
                return ((string)(this["NewsDBConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:lazynews.database.windows.net;Initial Catalog=NewsDB;User ID=lazy" +
            "news;Password=1CalOmE6TKxio2O!k2")]
        public string NewsDBConnectionString3 {
            get {
                return ((string)(this["NewsDBConnectionString3"]));
            }
        }
    }
}
